```{r setup, echo = F}
library(tidyverse)
library(ggplot2)
library(readr)
library(survivoR)
library(forcats)
library(ggthemes)
library(randomForest)
library(caret)
library(dplyr)

```

Data Cleaning
```{r}
castaway_full <- merge(x = castaways, y = castaway_details)

castaway_full <- castaway_full %>%
  mutate(season_area = case_when(season < 10 ~ "initial", season < 20 ~ "early", season < 30 ~"middle", season < 40 ~ "late", TRUE ~ "present"))
castaway_full <- castaway_full %>%
  mutate(finalist = ifelse(place <= 3, TRUE, FALSE))

castaway_full <- castaway_full%>%
  mutate(age_group = case_when(age < 25 ~ "very young", age < 30 ~ "young", age < 35 ~ "average", age < 40 ~ "older", age < 45 ~ "pretty old", age <50 ~ "old", age < 60 ~ "very old", TRUE ~ "elderly"))

#Removing all NAs for personality types from dataset.
castaway_filtered <- castaway_full %>%
  filter(!is.na(personality_type))

castaway_filtered <- castaway_filtered[,c(1,2,4,6,7,15,17,18,19,31,36,37,38,39,40,46,47)]
castaway_filtered <- castaway_filtered %>%
  mutate(collar = case_when(grepl("Student", occupation) ~ "Student", TRUE ~ collar))

castaway_filtered <- castaway_filtered %>%
  mutate(Energy = case_when(grepl("I", personality_type) ~ "Introverted", TRUE ~ "Extroverted"))

castaway_filtered <- castaway_filtered %>%
  mutate(Mind = case_when(grepl("N", personality_type) ~ "Intuitive", TRUE ~ "Observing"))

castaway_filtered <- castaway_filtered %>%
  mutate(Nature = case_when(grepl("T", personality_type) ~ "Thinking", TRUE ~ "Feeling"))

castaway_filtered <- castaway_filtered %>%
  mutate(Tactics = case_when(grepl("J", personality_type) ~ "Judging", TRUE ~ "Prospecting"))

#creating test datasets for seasons 48 and 50

castaway_50 <- castaway_full %>%
  filter(season == "50")
castaway_50 <- rbind(castaway_full[c(550,1231,1138),], castaway_50)
castaway_50 <- castaway_50 %>%
  slice(-24,-25)
castaway_50$age <- c(47,45,31,35,39,53,27,54,39,55,51,28,30,34,45,32,31,31,54,43,31,41,26,34)
castaway_50[3,38] <- "ESTJ"
castaway_50[23,38] <- "ENTP"
castaway_50[c(3,23),40] <- "White collar"
castaway_50[c(1,2),46] <- "present"

castaway_50 <- castaway_50%>%
  mutate(age_group = case_when(age < 25 ~ "very young", age < 30 ~ "young", age < 35 ~ "average", age < 40 ~ "older", age < 45 ~ "pretty old", age <50 ~ "old", age < 60 ~ "very old", TRUE ~ "elderly"))

castaway_50 <- castaway_50[,c(1,2,4,6,7,15,17,18,19,31,36,37,38,39,40,46,47)]
castaway_filtered <- castaway_filtered %>%
  mutate(collar = case_when(grepl("Student", occupation) ~ "Student", TRUE ~ collar))

castaway_50 <- castaway_50 %>%
  mutate(Energy = case_when(grepl("I", personality_type) ~ "Introverted", TRUE ~ "Extroverted"))

castaway_50 <- castaway_50 %>%
  mutate(Mind = case_when(grepl("N", personality_type) ~ "Intuitive", TRUE ~ "Observing"))

castaway_50 <- castaway_50 %>%
  mutate(Nature = case_when(grepl("T", personality_type) ~ "Thinking", TRUE ~ "Feeling"))

castaway_50 <- castaway_50 %>%
  mutate(Tactics = case_when(grepl("J", personality_type) ~ "Judging", TRUE ~ "Prospecting"))


#Deleting seasons 49-50 since 49 already didn't include personality types. Only keeping US for same reason

castaway_filtered <- castaway_filtered %>%
  filter(!season == "50")

castaway_filtered <- castaway_filtered %>%
  filter(!version == "AU")

#Only 851 rows remain after data cleaning. We started with 1378.

castaway_filtered <- castaway_filtered %>%
  arrange(castaway_id)


```


Prediction Model
```{r}
# Train/test split
set.seed(472)
Model_Train <- sample(1:nrow(castaway_filtered), 0.7 * nrow(castaway_filtered))
testing_data <- castaway_filtered[-Model_Train,]

# Make outcome a factor
training_data$finalist <- as.factor(training_data$finalist)
testing_data$finalist <- as.factor(testing_data$finalist)

# Seeds
seeds <- c(2026, 411, 235, 332, 421)

# Train models
models <- lapply(seeds, function(s) {
  set.seed(s)
  Model_Train <- sample(1:nrow(castaway_filtered), 0.7 * nrow(castaway_filtered))
  training_data <- castaway_filtered[Model_Train,]
  training_data$finalist <- as.factor(training_data$finalist)
  randomForest(
    finalist ~ Energy + Mind + Nature + age_group + season_area + 
      Tactics + gender + lgbt + collar + bipoc,
    data = training_data
  )
})

# Get binary predictions per model
pred_matrix <- sapply(models, function(model) {
  probs <- predict(model, testing_data, type = "prob")[, 2]
  probs > 0.25
})

# Majority vote
final_preds <- apply(pred_matrix, 1, function(x) {
  mean(x) > 0.5
})

# Match factor levels
factored <- factor(final_preds, levels = levels(testing_data$finalist))
# Confusion matrix
IDK <- confusionMatrix(factored, testing_data$finalist)


```

```{r}
#graph
frame <- as.data.frame(as.table(IDK))

ggplot(data = frame, aes(x = Prediction, y = Reference, fill = Freq,)) +
  geom_tile() +
  scale_fill_distiller(palette = "YlGn") +
  scale_x_discrete(limits = c("TRUE", "FALSE")) +
  scale_y_discrete(limits = c("FALSE", "TRUE")) +
  geom_text(aes(label = Freq),colour = "skyblue1") +
  theme_economist()

ggsave("confusion.jpg")
IDK
```