---
title: "survival_model"
output: html_document
---

# libraries

```{r}
library(dplyr)
library(broom)
library(survivoR)
library(survival)
library(knitr)
library(kableExtra)
library(ggsurvfit)
```

## Cleaning

```{r}
# processing
data(challenge_results)
data(boot_order)
data(castaways)
```

```{r}
challenge_results <- challenge_results |> 
  filter(!(season == 50) & (version == "US") & !(challenge_type == "Duel")) |>
  group_by(castaway_id, season) |>
  summarise(challenges_won = sum(won),
         individual_immunity_won = sum(won_individual_immunity),
         tribal_immunity_won = sum(won_tribal_immunity),
         tribal_reward_won = sum(won_tribal_reward),
         individual_reward_won = sum(won_individual_reward),
         .groups = "drop") 


boot_order <- boot_order |> 
  filter(!(season == 50) & (version == "US")) |>
  select(c(castaway_id, season, day, order)) |>
  distinct(season, castaway_id, .keep_all = TRUE)

castaways <- castaways |>
  filter(!(season == 50) & (version == "US")) |>
  select(c(season, castaway_id, place, castaway)) |>
  distinct(season, castaway_id, castaway, .keep_all = TRUE)
```

```{r}
## adding back in castaways != Duel removed
us0195 <- data.frame(castaway_id = "US0195", season = 27, challenges_won = 1,
                     individual_immunity_won = 0, tribal_immunity_won = 0,
                     tribal_reward_won = 0, individual_reward_won = 0)

us0107 <- data.frame(castaway_id = "US0107", season = 27, challenges_won = 0,
                     individual_immunity_won = 0, tribal_immunity_won = 0,
                     tribal_reward_won = 0, individual_reward_won = 0)

challenge_results <- rbind(challenge_results, us0195)
challenge_results <- rbind(challenge_results, us0107)
```

# Now we merge

```{r}
join1 <- inner_join(challenge_results, boot_order, by = c("castaway_id", "season"))
# column day is day eliminated, order is order eliminated, opposite to placement
survival_data <- inner_join(join1, castaways, by = c("castaway_id", "season"))

# making colnames clearer
colnames(survival_data) <- c("castaway_id", "season", "challenges_won",
                             "individual_immunity_won", "tribal_immunity_won",
                             "tribal_reward_won", "individual_reward_one", "day_eliminated",
                             "order_eliminated", "placement", "castaway")
```

## status variable

```{r}
survival_data <- survival_data |>
  mutate(status = if_else(placement == 1, FALSE, TRUE))
```

## Save season 48 for testing

```{r}
season48 <- survival_data |>
  filter(season == 48)

# get rid of season 48 from combined_data
survival_data <- survival_data |>
  filter(!(season == 48))
```

## Cox Regression

```{r}
survivor_cox <- coxph(Surv(day_eliminated, status) ~ tribal_immunity_won + individual_immunity_won + tribal_reward_won + individual_reward_one, data = survival_data)

zph <- cox.zph(survivor_cox)
data.frame(zph$table) |>
  mutate(predictors = c("Tribal Immunity Won", "Individual Immunity Won", "Tribal Reward Won", "Individual Reward Won", "Global"), .before = chisq, p = scales::pvalue(p)) |> 
  kable(
    digits=c(3,3,3),
    row.names = F,
    col.names = c("Predictors", "Chi Square", "df", "p value")
  )
#save_kable(kable_zph, file = "cox_assumptions_table.png")
```

```{r}
#Median survival curve
avg_survival <- survfit(survivor_cox)
plot(avg_survival)

#Survival, No challenges won
newdata <- data.frame(
  tribal_immunity_won = 0,
  individual_immunity_won = 0,
  tribal_reward_won = 0,
  individual_reward_one = 0
)
no_chal_survival <- survfit(survivor_cox, newdata)
plot(no_chal_survival)

```

```{r}
surv_cox_time <- coxph(Surv(day_eliminated, status) ~ challenges_won + tt(challenges_won), data = survival_data, tt = function(x,t,...) x*t)

summary(surv_cox_time)

```

```{r}

survival_data_rates <- survival_data |>
  group_by(season) |>
  mutate(chal_rate = challenges_won / day_eliminated)

surv_rate <- coxph(Surv(day_eliminated, status) ~ chal_rate, data = survival_data_rates)

plot(cox.zph(surv_rate))

```

# Survival

```{r}
str1 <- survfit(Surv(day_eliminated, status) ~ 1, data = survival_data)
tidy(str1)
```

```{r}
survfit2(Surv(day_eliminated, status) ~ 1, data = survival_data) |> ggsurvfit()
```
